root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ."
bin = "./tmp/server"
include_ext = ["go", "html"]
exclude_dir = ["tmp"]
delay = 500

[log]
time = true

[misc]
clean_on_exit = true
